#!/bin/bash
WATER="water"; STIR="stir."; water_value=$((5#$(echo $WATER | tr 'water' '01234'))); stir_value=$((5#$(echo $STIR | tr 'stir.' '01234'))); result=$((water_value + stir_value)); result_base8=$(printf "%o" $result); final_output=$(echo $result_base8 | tr '01234567' 'bestchol'); echo "Result in base bestchol: $final_output"

